apiVersion: v1
kind: Service
metadata:
  name: slb
  labels:
    app: slbdemo
    group: com.example
    provider: fabric8
    version: 0.0.1-SNAPSHOT 
spec:
  ports:
  - name: amqps
    port: 5671
  loadBalancerIP:
  type: LoadBalancer 
  selector:
    app: slbdemo
    deploymentconfig: slbdemo
    group: com.example
    provider: fabric8
    version: 0.0.1-SNAPSHOT
